apidocs/modules/api/models.py
from flask import (
        Blueprint
)

bp = Blueprint('api_model', __name__)

class ApiModel:
    def __init__(self, method, path, summary, yamlfile, yamlstream):
        self.method = method
        self.path = path
        self.summary = summary
        self.yamlfile = yamlfile
        self.yamlstream = yamlstream
        #self.description = description
        #self.path_params = path_params
        #self.body_params = body_params
        #self.responses = responses
    
    def get_model(self):
        model = {
            "method": self.method,
            "path": self.path,
            "summary": self.summary,
            "yamlfile": self.yamlfile,
            "yamlstream": self.yamlstream
        }

        return model

apidocs/modules/api/controllers.py
from flask import (
        Blueprint, render_template, url_for, send_file, flash, redirect
)
import os
import yaml

from apidocs.helpers.pagination import Pagination
from apidocs.modules.access_control.manager import login_required
from apidocs.db.mongodb import MongoDb
from apidocs.helpers.utils import yml_path
from apidocs.modules.http_methods.controllers import get_http_methods, get_http_method_by_key

bp = Blueprint('api_controller', __name__)
db_apis = MongoDb('apis')

### API METHODS ###

def get_apis(page_num=1):
    sort = [( 'method', 1),( 'path', 1)]

    db_apis.set_page_num(page_num)
    return db_apis.get_all(sort), db_apis.count_total()

def write_api(api):
    result = db_apis.insert(api)
    
    return result

def update_api(api):
    result = db_apis.update(api)
    
    return result

def get_api_by_id(id):
    return db_apis.get_by_id(id)

def get_apis_by_method(method, page_num):
    filter = { 'method' : method }

    db_apis.set_page_num(page_num)
    return db_apis.get_all_by_filter(filter), db_apis.count_total(filter)

def get_apis_by_keywords(keyword):
    filtered_apis = None

    if keyword or keyword.strip():
        filter = { "$or": [ { 'path' : { '$regex' : keyword, "$options" : "i" } },  { 'summary' : { '$regex' : keyword, "$options" : "i" } } ] }        
        filtered_apis = db_apis.get_all_by_filter(filter)

    return filtered_apis    

def get_api_by_path_and_method(api):
    filter = { 'path': api['path'], 'method' : api['method'] }
    return db_apis.get_all_by_filter(filter)

def api_already_exists(api):
    filtered_apis = get_api_by_path_and_method(api)

    if filtered_apis.count() > 0:
        return True
    else:
        return False

def get_static_yaml_file(api_id):
    return url_for('static', filename='yml/{}.yaml'.format(api_id))

def get_yaml_file(api_id):
    file = os.path.join(yml_path(), "{}.yaml".format(api_id))
    
    if os.path.exists(file):
        return file
    else: #TODO: Ainda com erro quando o arquivo YAML não existe mais na pasta, rever bloco abaixo
        try:
            api = get_api_by_id(api_id)
            yamlstream = api["yamlstream"]
            return save_yml_to_directory(api_id, yamlstream)
        except:
            return None

def save_yml_to_directory(api_id, yamlstream):
    try:
        file = os.path.join(yml_path(), "{}.yaml".format(api_id))

        with open(file, 'w') as outfile:
            yaml.safe_dump(yamlstream, outfile, default_flow_style=True)
        
        return outfile
    except:
        return None

def download_yaml_file(api_id):
    file = get_yaml_file(api_id)

    if file: 
        return file
    
    flash("Não foi possível recuperar o YAML dessa API, tente novamente!", "error")
    return None

### CSS METHODS ####

def css_button_class(method):
    method = get_http_method_by_key(method)
    css = ''

    if method:
        css = method['button_class']

    return css

def css_div_class(method):
    method = get_http_method_by_key(method)
    css = ''

    if method:
        css = method['div_class']

    return css

#### VIEW ROUTES ###

@bp.route("/api/list", defaults={'page_num' : 1})
@bp.route("/api/list/<int:page_num>")
@login_required
def api_list(page_num):
    apis, total_apis = get_apis(page_num)
    http_methods = get_http_methods()
    pagination = Pagination(total_apis, page_num)
  
    return render_template('api/list.html', pagination=pagination, apis=apis, method=None, http_methods=http_methods, css_button_class=css_button_class, css_div_class=css_div_class)

@bp.route("/api/list/<string:method>", defaults={'page_num' : 1})
@bp.route("/api/list/<string:method>/<int:page_num>")
@login_required
def api_list_by_method(method, page_num):
    apis, total_apis = get_apis_by_method(method, page_num)
    http_methods = get_http_methods()
    pagination = Pagination(total_apis, page_num)

    return render_template('api/list.html', pagination=pagination, apis=apis, method=method, http_methods=http_methods, css_button_class=css_button_class, css_div_class=css_div_class)

@bp.route("/api/detail/<string:id>")
@login_required
def api_detail(id):
    try:
        api = get_api_by_id(id)
        yaml_file = get_static_yaml_file(api['_id'])
    except:
        api = None
        yaml_file = None
    
    return render_template('api/detail-swagger.html', api=api, yaml_file=yaml_file)

@bp.route("/api/download/<string:id>")
@login_required
def download_api_yaml(id):
    file = download_yaml_file(id)

    if file:
        return send_file(file, as_attachment=True)
    
    return redirect(url_for('api_controller.api_detail', id=id))

apidocs/templates/api/detail-swagger.html
{% extends 'base/template.html' %}

{% block header %}
  {% block title %}Detalhes da API - <span class="small">by <a href="https://swagger.io/tools/swagger-ui/">Swagger UI</a></span>{% endblock %}
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='vendor/swagger-ui/3.2.2/css/swagger-ui.css') }}" >
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/apidocs-swagger-ui.css') }}" >
{% endblock %}

{% block button_back %}

{% if api %}

  <a href="{{ url_for('api_controller.download_api_yaml', id=api['_id']) }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
      <i class="fas fa-download fa-sm text-white-50"></i> Download YAML
  </a>

{% endif %}

{% endblock %}

{% block content %}

{% if api %}

  <div id="swagger-ui"></div>

  {% block script %}

  <script src="{{ url_for('static', filename='vendor/swagger-ui/3.2.2/js/swagger-ui-bundle.js') }}"> </script>
  <script src="{{ url_for('static', filename='vendor/swagger-ui/3.2.2/js/swagger-ui-standalone-preset.js') }}"> </script>
  <script>
  window.onload = function() {
    var url = '{{ yaml_file }}';

    window.ui = buildSwaggerUI(url);
  }
  </script>

  {% endblock %}

{% else %}

  <div class="card mb-4 py-3 border-left-warning text-center">Dados inválidos</div>

{% endif %}

{% endblock %}

apidocs/templates/api/detail.html
{% extends 'base/template.html' %}

{% block header %}
  {% block title %}Detalhes da API{% endblock %}
{% endblock %}

{% block content %}

{% if api == None %}

<div class="card mb-4 py-3 border-left-warning text-center">Dados inválidos</div>

{% else %}

<div class="row">
  <div class="col-lg-12">
    <div class="card mb-2 {{ css_div_class(api['method']) }}">
      <div class="nav-link">
        <div class="btn {{ css_button_class(api['method']) }} btn-sm">
          <span class="text">{{ api['method'] }}</span>
        </div>
        <span class="font-weight-bolder text-black-50 m-1">{{ api['path'] }}</span>
        <span class="text-black-50 m-1">{{ api['summary'] }}</span>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-10 pt-2 text-justify">
    <span class="text">{{ api['description'] }}</span>
  </div>
  <div class="col-lg-2 text-right">
    <a class="nav-link" href="#">
      <span class="icon text-black-50">
        <i class="fas fa-fw fa-download"></i>
        YAML
      </span>
    </a>
  </div>  
</div>

<hr/>

<div class="row">
  <div class="col-lg-12">
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Paramêtros</h6>
      </div>
      <div class="card-body">

        <table class="table table-bordered dataTable">
          <thead>
            <tr role="row">
              <th>Nome</th>
              <th>Descrição</th>
            </tr>
          </thead>
          <tbody>
            {% for param in api['path-params'] %}
            <tr role="row" class="even">
              <td>
                <div>
                  <span class="font-weight-bold">{{ param['name'] }}</span><span class="small font-weight-bold text-danger">{% if param['required'] == True %} * Obrigatório{% endif %}</span>
                </div>
                <div>
                  <span class="font-weight-bold small">{{ param['type'] }}</span>
                </div>
                <div>
                  <span class="text-gray-600 small">(path)</span>
                </div>              
              </td>
              <td><span class="small">{{ param['description'] }}</span></td>
            </tr>
            {% endfor %}

            {% if api['body-params'] != None %}
            <tr role="row" class="even">
              <td rowspan="2">
                <div>
                  <span class="font-weight-bold">{{ api['body-params']['name'] }}</span><span class="small font-weight-bold text-danger">{% if api['body-params']['required'] == True %} * Obrigatório{% endif %}</span>
                </div>
                <div>
                  <span class="text-gray-600 small">(body)</span>
                </div>
              </td>
              <td><span class="small">{{ api['body-params']['description'] }}</span></td>
            </tr>
            <tr role="row" class="even">
              <td>
                <div class="font-weight-bold small p-1">Exemplo:</div>
                <div>
                  <pre class="bg-gray-900 text-gray-100 p-2 m-1" id="body_example_json">{{ json.dumps(api['body-params']['example'], indent=4) }}</pre>
                </div>
              </td>
            </tr>
            <tr role="row" class="even">
              <td colspan="2" class="small p-1 text-right"><span class="font-weight-bold">Content-Type: </span>{{ api['body-params']['content-type'] }}</td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">

    {% if api['responses'] != None %}

    <!-- Basic Card Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Response</h6>
      </div>
      <div class="card-body">

        <table class="table table-bordered dataTable">
          <thead>
            <tr role="row">
              <th>Código</th>
              <th>Descrição</th>
            </tr>
          </thead>
          <tbody>        
            {% for response in api['responses']["response"] %}
            <tr role="row" class="even">
              <td>
                <span class="font-weight-bold small">{{ response['code'] }}</span>
              </td>
              <td>
                <div class="small p-2 m-1 bg-gray-900 text-gray-100">{{ response['description'] }}</div>
                <div class="font-weight-bold small p-1">Exemplo:</div>
                <div>
                  <pre class="bg-gray-900 text-gray-100 p-2 m-1" id="body_example_json">{{ json.dumps(response['example'], indent=4) }}</pre>
                </div>
              </td>
            </tr>
            {% endfor %}
            <tr role="row" class="even">
              <td colspan="2" class="small p-1 text-right"><span class="font-weight-bold">Content-Type: </span>{{ api['responses']["content-type"] }}</td>
            </tr>          
          </tbody>
        </table>      

      </div>
    </div>

    {% endif %}

  </div>
</div>

{% endif %}

{% endblock %}

apidocs/templates/api/list.html
{% import "macros/_macros.html" as macros %}
{% extends 'base/template.html' %}

{% block header %}
  {% block title %}Lista de API's{% endblock %}
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-lg-5">
		<div class="card shadow mb-4">
			<!-- Card Header - Accordion -->
			<a href="#collapseCardMethodFilter" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardMethodFilter">
				<span class="icon">
					<i class="fas fa-filter"></i>
				</span>
				<span class="m-0 font-weight-bold text-primary">Filtros</span>
			</a>
			<!-- Card Content - Collapse -->
			<div class="collapse" id="collapseCardMethodFilter">
				<div class="card-body row">
					<label class="col-lg-3 small font-weight-bolder py-2">Métodos HTTP:</label>
					<div class="col-lg-9">
						{% for http_method in http_methods %}
						<a href="{{ url_for('api_controller.api_list_by_method', method=http_method['method']) }}" class="btn {{ http_method['button_class'] }} btn-sm">
							<span class="text">{{ http_method['method'] }}</span>
						</a>
						{% endfor %}
						<a href="{{ url_for('api_controller.api_list') }}">Ver todas</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% if apis.count() > 0 %}
<div class="row">
	<div class="col-lg-12">
		{% for api in apis %}
		<div class="card mb-2 {{ css_div_class(api['method']) }}">
			<a class="nav-link" href="{{ url_for('api_controller.api_detail', id=api['_id']) }}">
				<div class="btn {{ css_button_class(api['method']) }} btn-sm">
					<span class="text">{{ api['method'] }}</span>
				</div>
				<span class="font-weight-bolder text-black-50 m-1">{{ api['path'] }}</span>
				<span class="text-black-50 m-1">{{ api['summary'] }}</span>
				<span class="icon text-black-50">
					<i class="fas fa-fw fa-angle-right"></i>
				</span>				
			</a>
		</div>
		{% endfor %}
	</div>
</div>

{% if method %}
{{ macros.pagination_widget(pagination.pages_array, pagination.actual_page, 'api_controller.api_list_by_method', method=method) }}
{% else %}
{{ macros.pagination_widget(pagination.pages_array, pagination.actual_page, 'api_controller.api_list') }}
{% endif %}

{% else %}
<div class="card mb-4 py-3 border-left-warning text-center">Sem registros de APIs para serem exibidos, no momento!</div>
{% endif %}

{% endblock %}

{% block script %}

{% endblock %}