apidocs/modules/api/controllers.py
from flask import (
        Blueprint, render_template, url_for, send_file, flash, redirect
)
import os
import yaml

from apidocs.helpers.pagination import Pagination
from apidocs.modules.access_control.manager import login_required
from apidocs.db.mongodb import MongoDb
from apidocs.helpers.utils import yml_path
from apidocs.modules.http_methods.controllers import get_http_methods, get_http_method_by_key

bp = Blueprint('api_controller', __name__)
db_apis = MongoDb('apis')

### API METHODS ###

def get_apis(page_num=1):
    sort = [( 'method', 1),( 'path', 1)]

    db_apis.set_page_num(page_num)
    return db_apis.get_all(sort), db_apis.count_total()

def write_api(api):
    result = db_apis.insert(api)
    
    return result

def update_api(api):
    result = db_apis.update(api)
    
    return result

def get_api_by_id(id):
    return db_apis.get_by_id(id)

def get_apis_by_method(method, page_num):
    filter = { 'method' : method }

    db_apis.set_page_num(page_num)
    return db_apis.get_all_by_filter(filter), db_apis.count_total(filter)

def get_apis_by_keywords(keyword):
    filtered_apis = None

    if keyword or keyword.strip():
        filter = { "$or": [ { 'path' : { '$regex' : keyword, "$options" : "i" } },  { 'summary' : { '$regex' : keyword, "$options" : "i" } } ] }        
        filtered_apis = db_apis.get_all_by_filter(filter)

    return filtered_apis    

def get_api_by_path_and_method(api):
    filter = { 'path': api['path'], 'method' : api['method'] }
    return db_apis.get_all_by_filter(filter)

def api_already_exists(api):
    filtered_apis = get_api_by_path_and_method(api)

    if filtered_apis.count() > 0:
        return True
    else:
        return False

def get_static_yaml_file(api_id):
    return url_for('static', filename='yml/{}.yaml'.format(api_id))

def get_yaml_file(api_id):
    file = os.path.join(yml_path(), "{}.yaml".format(api_id))
    
    if os.path.exists(file):
        return file
    else: #TODO: Ainda com erro quando o arquivo YAML não existe mais na pasta, rever bloco abaixo
        try:
            api = get_api_by_id(api_id)
            yamlstream = api["yamlstream"]
            return save_yml_to_directory(api_id, yamlstream)
        except:
            return None

def save_yml_to_directory(api_id, yamlstream):
    try:
        file = os.path.join(yml_path(), "{}.yaml".format(api_id))

        with open(file, 'w') as outfile:
            yaml.safe_dump(yamlstream, outfile, default_flow_style=True)
        
        return outfile
    except:
        return None

def download_yaml_file(api_id):
    file = get_yaml_file(api_id)

    if file: 
        return file
    
    flash("Não foi possível recuperar o YAML dessa API, tente novamente!", "error")
    return None

### CSS METHODS ####

def css_button_class(method):
    method = get_http_method_by_key(method)
    css = ''

    if method:
        css = method['button_class']

    return css

def css_div_class(method):
    method = get_http_method_by_key(method)
    css = ''

    if method:
        css = method['div_class']

    return css

#### VIEW ROUTES ###

@bp.route("/api/list", defaults={'page_num' : 1})
@bp.route("/api/list/<int:page_num>")
@login_required
def api_list(page_num):
    apis, total_apis = get_apis(page_num)
    http_methods = get_http_methods()
    pagination = Pagination(total_apis, page_num)
  
    return render_template('api/list.html', pagination=pagination, apis=apis, method=None, http_methods=http_methods, css_button_class=css_button_class, css_div_class=css_div_class)

@bp.route("/api/list/<string:method>", defaults={'page_num' : 1})
@bp.route("/api/list/<string:method>/<int:page_num>")
@login_required
def api_list_by_method(method, page_num):
    apis, total_apis = get_apis_by_method(method, page_num)
    http_methods = get_http_methods()
    pagination = Pagination(total_apis, page_num)

    return render_template('api/list.html', pagination=pagination, apis=apis, method=method, http_methods=http_methods, css_button_class=css_button_class, css_div_class=css_div_class)

@bp.route("/api/detail/<string:id>")
@login_required
def api_detail(id):
    try:
        api = get_api_by_id(id)
        yaml_file = get_static_yaml_file(api['_id'])
    except:
        api = None
        yaml_file = None
    
    return render_template('api/detail-swagger.html', api=api, yaml_file=yaml_file)

@bp.route("/api/download/<string:id>")
@login_required
def download_api_yaml(id):
    file = download_yaml_file(id)

    if file:
        return send_file(file, as_attachment=True)
    
    return redirect(url_for('api_controller.api_detail', id=id))

apidocs/modules/orch/controllers.py
from flask import (
        Blueprint, render_template
)

from apidocs.helpers.pagination import Pagination
from apidocs.helpers.utils import get_logged_username, get_datetime_now
from apidocs.modules.access_control.manager import login_required, editor_required
from apidocs.db.mongodb import MongoDb

bp = Blueprint('orch_controller', __name__)

db_orchs = MongoDb('orchs')
db_orchs_data = MongoDb('orchs_data')
db_orchs_history = MongoDb('orchs_history')

### METHODS ###

def get_published_orchs():
    filter = {'published': True}
    sort = [('name', 1), ('version', 1)]

    return db_orchs.get_all_by_filter(filter, sort)

def get_non_published_orchs():
    filter = {'published': False}
    sort = [('name', 1), ('version', 1)]

    return db_orchs.get_all_by_filter(filter, sort)

def get_published_orchs_distinct(page_num):
    distinct = 'name'
    filter = {'published': True}
    sort = {'name': 1}

    db_orchs.set_page_num(page_num)
    return db_orchs.get_all_distinct(distinct, filter, sort), db_orchs.count_total(filter, distinct)

def get_orch_by_id(id):
    return db_orchs.get_by_id(id)

def get_published_orchs_by_name(name, page_num):
    filter = { 'name' : name, 'published' : True }
    sort = [('name', 1), ('version', 1)]

    db_orchs.set_page_num(page_num)
    return db_orchs.get_all_by_filter(filter, sort), db_orchs.count_total(filter)

def get_orch_by_name_and_version(name, version):
    filter = { 'name' : name, 'version': version }

    return db_orchs.get_one_by_filter(filter)

def get_published_orchs_by_keywords(keyword):
    filtered_orchs = None

    if keyword or keyword.strip():
        filter = { "published" : True, "$or": [ { 'name' : { '$regex' : keyword, "$options" : "i" } },  { 'description' : { '$regex' : keyword, "$options" : "i" } } ] }
        filtered_orchs = db_orchs.get_all_by_filter(filter)

    return filtered_orchs

def orch_insert(orch):
    return db_orchs.insert(orch)

def orch_update(updated_orch):
    updated_orch['last_handler_user'] = get_logged_username()
    updated_orch['last_handler_date'] = get_datetime_now()

    return db_orchs.update(updated_orch)

#-- orchs data --#

def get_orch_data_by_id(id):
    return db_orchs_data.get_by_id(id)

def get_orch_data_by_orch_id(orch_id):
    filter = { 'orch_id' : orch_id }

    return db_orchs_data.get_one_by_filter(filter)

def orch_data_insert(orch_data):
    return db_orchs_data.insert(orch_data)

def orch_data_update(updated_orch_data):
    return db_orchs_data.update(updated_orch_data)

#-- orchs history --#

def get_orch_history_by_id(id):
    return db_orchs_history.get_by_id(id)

def get_orch_history_by_orch_id(orch_id):
    filter = { 'orch_id' : orch_id }

    return db_orchs_history.get_one_by_filter(filter)

def get_all_orch_history_by_orch_name(orch_name, orch_version):
    filter = { 'orch_name' : orch_name, 'orch_version' : { '$lte' : orch_version } }
    sort = [('orch_version', 1)]

    return db_orchs_history.get_all_by_filter(filter, sort)

def orch_history_insert(orch_history):
    return db_orchs_history.insert(orch_history)

def orch_history_update(updated_orch_history):
    return db_orchs_history.update(updated_orch_history)

### ROUTES ###


@bp.route("/orch/list", defaults={'page_num' : 1})
@bp.route("/orch/list/<int:page_num>")
@login_required
@editor_required
def orch_list(page_num):
    orchs, total_orchs = get_published_orchs_distinct(page_num)
    orchs_count = len(orchs)
    pagination = Pagination(total_orchs, page_num)

    return render_template('orch/list.html', pagination=pagination, orchs=orchs, orchs_count=orchs_count)


@bp.route("/orch/<string:orch_name>/versions", defaults={'page_num' : 1})
@bp.route("/orch/<string:orch_name>/versions/<int:page_num>")
@login_required
@editor_required
def orch_version_list(orch_name, page_num):
    orchs, total_orchs = get_published_orchs_by_name(orch_name, page_num)
    pagination = Pagination(total_orchs, page_num)

    return render_template('orch/version.html', pagination=pagination, orch_name=orch_name, orchs=orchs)


@bp.route("/orch/detail/<string:id>")
@login_required
@editor_required
def orch_detail(id):
    orch = get_orch_by_id(id)
    orch_data = get_orch_data_by_orch_id(id)
    orch_histories = None

    if orch:
        orch_histories = get_all_orch_history_by_orch_name(orch['name'], orch['version'])

    return render_template('orch/detail.html', orch=orch, orch_data=orch_data, orch_histories=orch_histories)

apidocs/modules/service/controllers.py
from flask import (
        Blueprint, render_template
)
from markupsafe import Markup

from apidocs.helpers.pagination import Pagination
from apidocs.helpers.utils import get_logged_username, get_datetime_now
from apidocs.modules.access_control.manager import login_required, editor_required
from apidocs.db.mongodb import MongoDb

bp = Blueprint('service_controller', __name__)

db_services = MongoDb('services')
db_services_data = MongoDb('services_data')
db_services_history = MongoDb('services_history')

### METHODS ###

def get_published_services():
    filter = {'published': True, 'is_queue' : False}
    sort = [('name', 1), ('version', 1)]

    return db_services.get_all_by_filter(filter, sort)

def get_published_rmq_services():
    filter = {'published': True, 'is_queue' : True}
    sort = [('name', 1), ('version', 1)]

    return db_services.get_all_by_filter(filter, sort)

def get_non_published_services():
    filter = {'published': False}
    sort = [('name', 1), ('version', 1)]

    return db_services.get_all_by_filter(filter, sort)

def get_published_services_distinct(page_num):
    distinct = 'name'
    filter = {'published': True, 'is_queue' : False}
    sort = {'name': 1}

    db_services.set_page_num(page_num)
    return db_services.get_all_distinct(distinct, filter, sort), db_services.count_total(filter, distinct)

def get_published_rmq_services_distinct(page_num):
    distinct = 'name'
    filter = {'published': True, 'is_queue' : True}
    sort = {'name': 1}

    db_services.set_page_num(page_num)
    return db_services.get_all_distinct(distinct, filter, sort), db_services.count_total(filter, distinct)

def get_service_by_id(id):
    return db_services.get_by_id(id)

def get_published_services_by_name(name, page_num):
    filter = { 'name' : name, 'published' : True, 'is_queue' : False }
    sort = [('name', 1), ('version', 1)]

    db_services.set_page_num(page_num)
    return db_services.get_all_by_filter(filter, sort), db_services.count_total(filter)

def get_published_rmq_services_by_name(name, page_num):
    filter = { 'name' : name, 'published' : True, 'is_queue' : True }
    sort = [('name', 1), ('version', 1)]

    db_services.set_page_num(page_num)
    return db_services.get_all_by_filter(filter, sort), db_services.count_total(filter)

def get_service_by_name_and_version(name, version):
    filter = { 'name' : name, 'version': version }

    return db_services.get_one_by_filter(filter)

def get_published_services_by_keywords(keyword):
    filtered_services = None

    if keyword or keyword.strip():
        filter = { "published" : True, 'is_queue' : False, "$or": [ { 'name' : { '$regex' : keyword, "$options" : "i" } },  { 'description' : { '$regex' : keyword, "$options" : "i" } } ] }
        filtered_services = db_services.get_all_by_filter(filter)

    return filtered_services

def get_published_rmq_services_by_keywords(keyword):
    filtered_services = None

    if keyword or keyword.strip():
        filter = { "published" : True, 'is_queue' : True, "$or": [ { 'name' : { '$regex' : keyword, "$options" : "i" } },  { 'description' : { '$regex' : keyword, "$options" : "i" } } ] }
        filtered_services = db_services.get_all_by_filter(filter)

    return filtered_services

def service_insert(service):
    return db_services.insert(service)

def service_update(updated_service):
    updated_service['last_handler_user'] = get_logged_username()
    updated_service['last_handler_date'] = get_datetime_now()

    return db_services.update(updated_service)

#-- services data --#

def get_service_data_by_id(id):
    return db_services_data.get_by_id(id)

def get_service_data_by_service_id(service_id):
    filter = { 'service_id' : service_id }

    return db_services_data.get_one_by_filter(filter)

def service_data_insert(service_data):
    return db_services_data.insert(service_data)

def service_data_update(updated_service_data):
    return db_services_data.update(updated_service_data)

#-- services history --#

def get_service_history_by_id(id):
    return db_services_history.get_by_id(id)

def get_service_history_by_service_id(service_id):
    filter = { 'service_id' : service_id }

    return db_services_history.get_one_by_filter(filter)

def get_all_service_history_by_service_name(service_name, service_version):
    filter = { 'service_name' : service_name, 'service_version' : { '$lte' : service_version } }
    sort = [('service_version', 1)]

    db_services_history.set_no_pagination(True)
    return db_services_history.get_all_by_filter(filter, sort)

def service_history_insert(service_history):
    return db_services_history.insert(service_history)

def service_history_update(updated_service_history):
    return db_services_history.update(updated_service_history)


### ROUTES ###

@bp.route("/service/list", defaults={'page_num' : 1})
@bp.route("/service/list/<int:page_num>")
@login_required
@editor_required
def service_list(page_num):
    services, total_services = get_published_services_distinct(page_num)
    services_count = len(services)

    pagination = Pagination(total_services, page_num)

    return render_template('service/list.html', rmq=False, pagination=pagination, services=services, services_count=services_count)


@bp.route("/service/<string:service_name>/versions", defaults={'page_num' : 1})
@bp.route("/service/<string:service_name>/versions/<int:page_num>")
@login_required
@editor_required
def service_version_list(service_name, page_num):
    services, total_services = get_published_services_by_name(service_name, page_num)

    pagination = Pagination(total_services, page_num)

    return render_template('service/version.html', pagination=pagination, rmq=False, service_name=service_name, services=services)


@bp.route("/service/detail/<string:id>")
@login_required
@editor_required
def service_detail(id):
    service = get_service_by_id(id)
    service_data = get_service_data_by_service_id(id)
    service_histories = None

    if service:
        service_histories = get_all_service_history_by_service_name(service['name'], service['version'])

    return render_template('service/detail.html', rmq=False, service=service, service_data=service_data, service_histories=service_histories, Markup=Markup)


@bp.route("/queue/list", defaults={'page_num' : 1})
@bp.route("/queue/list/<int:page_num>")
@login_required
@editor_required
def rmq_service_list(page_num):
    services, total_services = get_published_rmq_services_distinct(page_num)
    services_count = len(services)
    pagination = Pagination(total_services, page_num)

    return render_template('service/list.html', pagination=pagination, rmq=True, services=services, services_count=services_count)


@bp.route("/queue/<string:service_name>/versions", defaults={'page_num' : 1})
@bp.route("/queue/<string:service_name>/versions/<int:page_num>")
@login_required
@editor_required
def rmq_service_version_list(service_name, page_num):
    services, total_services = get_published_rmq_services_by_name(service_name, page_num)

    pagination = Pagination(total_services, page_num)

    return render_template('service/version.html', pagination=pagination, rmq=True, service_name=service_name, services=services)


@bp.route("/queue/detail/<string:id>")
@login_required
@editor_required
def rmq_service_detail(id):
    service = get_service_by_id(id)
    service_data = get_service_data_by_service_id(id)
    service_histories = None

    if service:
        service_histories = get_all_service_history_by_service_name(service['name'], service['version'])

    return render_template('service/detail.html', rmq=True, service=service, service_data=service_data, service_histories=service_histories, Markup=Markup)

apidocs/templates/base/flash-messages.html
{% for message in get_flashed_messages(category_filter=["error"]) %}
<div class="row justify-content-center">
    <div class="col-xl-12 col-lg-12 col-md-12">
        <div class="card border-left-danger text-center text-danger small">{{ message }}</div>
    </div>
</div>
{% endfor %}

{% for message in get_flashed_messages(category_filter=["success"]) %}
<div class="row justify-content-center">
    <div class="col-xl-12 col-lg-12 col-md-12">
        <div class="card border-left-success text-center text small">{{ message }}</div>
    </div>
</div>
{% endfor %}

{% for message in get_flashed_messages(category_filter=["info"]) %}
  <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="infoModalLabel">Mensagem do Sistema</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">{{ message }}</div>
        <div class="modal-footer text-center">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Fechar</button>
        </div>
      </div>
    </div>
  </div>
{% endfor %}

apidocs/templates/base/index.html
{% extends 'base/template.html' %}

{% block header %}
  {% block title %}Home{% endblock %}
{% endblock %}

{% block button_back %}

<a href="{{ url_for('register_controller.new_user_register') }}" class="btn btn-primary btn-icon-split btn-sm">
  <span class="icon text-white-50">
    <i class="fas fa-fw fa-user"></i>
  </span>
  <span class="text">Criar novo usuário</span>
</a>

{% endblock %}

{% block content %}

<div class="row">

  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-primary shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">APIs</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ apisCount }}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-torii-gate fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% if g.user["profile"] == "A" or g.user["profile"] == "E" %}

  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-success shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Orquestradores</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ orchsCount }}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-sitemap fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-info shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Serviços</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ servicesCount }}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-server fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Pending Requests Card Example -->
  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-warning shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Filas</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ queues_count }}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-exchange-alt fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% else %}

  <div class="col-xl-3 col-md-6 mb-4">
    <div class="card border-left-success shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Usuários Ativos</div>
            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ users_count }}</div>
          </div>
          <div class="col-auto">
            <i class="fas fa-users fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endif %}

</div>

<div class="row">

  <div class="col-lg-6">

    <!-- Default Card Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">APIs</h6>
      </div>
      <div class="card-body">
        <div class="mb-2">
          Permite pesquisar e visualizar os dados de uma API.
        </div>
        <div class="mb-2">
          <a href="{{ url_for('api_controller.api_list') }}" class="btn btn-primary btn-icon-split btn-sm">
            <span class="icon text-white-50">
              <i class="fas fa-fw fa-torii-gate"></i>
            </span>
            <span class="text">Acessar APIs</span>
          </a>
        </div>
      </div>
    </div>

    {% if g.user["profile"] == "A" or g.user["profile"] == "E" %}

    <!-- Basic Card Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Orquestradores</h6>
      </div>
      <div class="card-body">
        <div class="mb-2">
          Permite pesquisar e visualizar os dados de um Orquestrador.
        </div>
        <div class="mb-2">
          <a href="{{ url_for('orch_controller.orch_list') }}" class="btn btn-primary btn-icon-split btn-sm">
            <span class="icon text-white-50">
              <i class="fas fa-fw fa-sitemap"></i>
            </span>
            <span class="text">Acessar Orquestradores</span>
          </a>
        </div>
      </div>
    </div>

    {% endif %}

  </div>

  <div class="col-lg-6">

    {% if g.user["profile"] == "A" or g.user["profile"] == "E" %}

    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Serviços</h6>
      </div>
      <div class="card-body">
        <div class="mb-2">
          Permite pesquisar e visualizar os dados de um Serviço.
        </div>
        <div class="mb-2">
          <a href="{{ url_for('service_controller.service_list') }}" class="btn btn-primary btn-icon-split btn-sm">
            <span class="icon text-white-50">
              <i class="fas fa-fw fa-server"></i>
            </span>
            <span class="text">Acessar Serviços</span>
          </a>
        </div>
      </div>
    </div>

    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Filas</h6>
      </div>
      <div class="card-body">
        <div class="mb-2">
          Permite pesquisar e visualizar os dados de um Serviço do tipo Fila.
        </div>
        <div class="mb-2">
          <a href="{{ url_for('service_controller.rmq_service_list') }}" class="btn btn-primary btn-icon-split btn-sm">
            <span class="icon text-white-50">
              <i class="fas fa-fw fa-exchange-alt"></i>
            </span>
            <span class="text">Acessar Filas</span>
          </a>
        </div>
      </div>
    </div>    

    {% endif %}
  </div>

</div>

{% endblock %}

{% block script %}
    <script type="text/javascript">
        $('#infoModal').modal('show');
    </script>
{% endblock %}

apidocs/templates/base/template-authentication.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Api Docs - {% block title %}{% endblock %}</title>

  <!-- Custom fonts for this template-->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{{ url_for('static', filename='css/sb-admin-2.css') }}" rel="stylesheet">

  <link rel="shortcut icon" type="image/ico" href="{{ url_for('static', filename='img/favicon.ico') }}"/>

</head>

<body class="bg-gradient-primary">

  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
  <script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{{ url_for('static', filename='vendor/jquery-easing/jquery.easing.min.js') }}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{{ url_for('static', filename='js/sb-admin-2.min.js') }}"></script>

  {% block script %}{% endblock %}

</body>

</html>