apidocs/modules/orch/controllers.py
from flask import (
        Blueprint, render_template
)

from apidocs.helpers.pagination import Pagination
from apidocs.helpers.utils import get_logged_username, get_datetime_now
from apidocs.modules.access_control.manager import login_required, editor_required
from apidocs.db.mongodb import MongoDb

bp = Blueprint('orch_controller', __name__)

db_orchs = MongoDb('orchs')
db_orchs_data = MongoDb('orchs_data')
db_orchs_history = MongoDb('orchs_history')

### METHODS ###

def get_published_orchs():
    filter = {'published': True}
    sort = [('name', 1), ('version', 1)]

    return db_orchs.get_all_by_filter(filter, sort)

def get_non_published_orchs():
    filter = {'published': False}
    sort = [('name', 1), ('version', 1)]

    return db_orchs.get_all_by_filter(filter, sort)

def get_published_orchs_distinct(page_num):
    distinct = 'name'
    filter = {'published': True}
    sort = {'name': 1}

    db_orchs.set_page_num(page_num)
    return db_orchs.get_all_distinct(distinct, filter, sort), db_orchs.count_total(filter, distinct)

def get_orch_by_id(id):
    return db_orchs.get_by_id(id)

def get_published_orchs_by_name(name, page_num):
    filter = { 'name' : name, 'published' : True }
    sort = [('name', 1), ('version', 1)]

    db_orchs.set_page_num(page_num)
    return db_orchs.get_all_by_filter(filter, sort), db_orchs.count_total(filter)

def get_orch_by_name_and_version(name, version):
    filter = { 'name' : name, 'version': version }

    return db_orchs.get_one_by_filter(filter)

def get_published_orchs_by_keywords(keyword):
    filtered_orchs = None

    if keyword or keyword.strip():
        filter = { "published" : True, "$or": [ { 'name' : { '$regex' : keyword, "$options" : "i" } },  { 'description' : { '$regex' : keyword, "$options" : "i" } } ] }
        filtered_orchs = db_orchs.get_all_by_filter(filter)

    return filtered_orchs

def orch_insert(orch):
    return db_orchs.insert(orch)

def orch_update(updated_orch):
    updated_orch['last_handler_user'] = get_logged_username()
    updated_orch['last_handler_date'] = get_datetime_now()

    return db_orchs.update(updated_orch)

#-- orchs data --#

def get_orch_data_by_id(id):
    return db_orchs_data.get_by_id(id)

def get_orch_data_by_orch_id(orch_id):
    filter = { 'orch_id' : orch_id }

    return db_orchs_data.get_one_by_filter(filter)

def orch_data_insert(orch_data):
    return db_orchs_data.insert(orch_data)

def orch_data_update(updated_orch_data):
    return db_orchs_data.update(updated_orch_data)

#-- orchs history --#

def get_orch_history_by_id(id):
    return db_orchs_history.get_by_id(id)

def get_orch_history_by_orch_id(orch_id):
    filter = { 'orch_id' : orch_id }

    return db_orchs_history.get_one_by_filter(filter)

def get_all_orch_history_by_orch_name(orch_name, orch_version):
    filter = { 'orch_name' : orch_name, 'orch_version' : { '$lte' : orch_version } }
    sort = [('orch_version', 1)]

    return db_orchs_history.get_all_by_filter(filter, sort)

def orch_history_insert(orch_history):
    return db_orchs_history.insert(orch_history)

def orch_history_update(updated_orch_history):
    return db_orchs_history.update(updated_orch_history)

### ROUTES ###


@bp.route("/orch/list", defaults={'page_num' : 1})
@bp.route("/orch/list/<int:page_num>")
@login_required
@editor_required
def orch_list(page_num):
    orchs, total_orchs = get_published_orchs_distinct(page_num)
    orchs_count = len(orchs)
    pagination = Pagination(total_orchs, page_num)

    return render_template('orch/list.html', pagination=pagination, orchs=orchs, orchs_count=orchs_count)


@bp.route("/orch/<string:orch_name>/versions", defaults={'page_num' : 1})
@bp.route("/orch/<string:orch_name>/versions/<int:page_num>")
@login_required
@editor_required
def orch_version_list(orch_name, page_num):
    orchs, total_orchs = get_published_orchs_by_name(orch_name, page_num)
    pagination = Pagination(total_orchs, page_num)

    return render_template('orch/version.html', pagination=pagination, orch_name=orch_name, orchs=orchs)


@bp.route("/orch/detail/<string:id>")
@login_required
@editor_required
def orch_detail(id):
    orch = get_orch_by_id(id)
    orch_data = get_orch_data_by_orch_id(id)
    orch_histories = None

    if orch:
        orch_histories = get_all_orch_history_by_orch_name(orch['name'], orch['version'])

    return render_template('orch/detail.html', orch=orch, orch_data=orch_data, orch_histories=orch_histories)

apidocs/modules/search/controllers.py
from flask import (
        Blueprint, render_template, request
)
from apidocs.modules.access_control.manager import login_required
from apidocs.modules.api.controllers import get_apis_by_keywords
from apidocs.modules.orch.controllers import get_published_orchs_by_keywords
from apidocs.modules.service.controllers import get_published_services_by_keywords, \
    get_published_rmq_services_by_keywords

bp = Blueprint('search_controller', __name__)

### ROUTES ###

@bp.route("/search/list", methods=('GET', 'POST'))
@login_required
def search_list():
    search_word = ''
    
    apis = None
    api_count = 0
    
    orchs = None
    orch_count = 0

    services = None
    service_count = 0

    queues = None
    queue_count = 0

    search_count = 0

    if request.method == 'POST':
        search_word = str(request.form['search_words'])

        apis = get_apis_by_keywords(search_word)
        api_count = 0 if apis == None else apis.count()

        orchs = get_published_orchs_by_keywords(search_word)
        orch_count = 0 if orchs == None else orchs.count()

        services = get_published_services_by_keywords(search_word)
        service_count = 0 if services == None else services.count()

        queues = get_published_rmq_services_by_keywords(search_word)
        queue_count = 0 if queues == None else queues.count()

        search_count = api_count + orch_count + service_count + queue_count

    return render_template('search/list.html', apis=apis, api_count=api_count, orchs=orchs, orch_count=orch_count, services=services, service_count=service_count, queues=queues, queue_count=queue_count, search_word=search_word, search_count=search_count)

apidocs/modules/service/controllers.py
from flask import (
        Blueprint, render_template
)
from markupsafe import Markup

from apidocs.helpers.pagination import Pagination
from apidocs.helpers.utils import get_logged_username, get_datetime_now
from apidocs.modules.access_control.manager import login_required, editor_required
from apidocs.db.mongodb import MongoDb

bp = Blueprint('service_controller', __name__)

db_services = MongoDb('services')
db_services_data = MongoDb('services_data')
db_services_history = MongoDb('services_history')

### METHODS ###

def get_published_services():
    filter = {'published': True, 'is_queue' : False}
    sort = [('name', 1), ('version', 1)]

    return db_services.get_all_by_filter(filter, sort)

def get_published_rmq_services():
    filter = {'published': True, 'is_queue' : True}
    sort = [('name', 1), ('version', 1)]

    return db_services.get_all_by_filter(filter, sort)

def get_non_published_services():
    filter = {'published': False}
    sort = [('name', 1), ('version', 1)]

    return db_services.get_all_by_filter(filter, sort)

def get_published_services_distinct(page_num):
    distinct = 'name'
    filter = {'published': True, 'is_queue' : False}
    sort = {'name': 1}

    db_services.set_page_num(page_num)
    return db_services.get_all_distinct(distinct, filter, sort), db_services.count_total(filter, distinct)

def get_published_rmq_services_distinct(page_num):
    distinct = 'name'
    filter = {'published': True, 'is_queue' : True}
    sort = {'name': 1}

    db_services.set_page_num(page_num)
    return db_services.get_all_distinct(distinct, filter, sort), db_services.count_total(filter, distinct)

def get_service_by_id(id):
    return db_services.get_by_id(id)

def get_published_services_by_name(name, page_num):
    filter = { 'name' : name, 'published' : True, 'is_queue' : False }
    sort = [('name', 1), ('version', 1)]

    db_services.set_page_num(page_num)
    return db_services.get_all_by_filter(filter, sort), db_services.count_total(filter)

def get_published_rmq_services_by_name(name, page_num):
    filter = { 'name' : name, 'published' : True, 'is_queue' : True }
    sort = [('name', 1), ('version', 1)]

    db_services.set_page_num(page_num)
    return db_services.get_all_by_filter(filter, sort), db_services.count_total(filter)

def get_service_by_name_and_version(name, version):
    filter = { 'name' : name, 'version': version }

    return db_services.get_one_by_filter(filter)

def get_published_services_by_keywords(keyword):
    filtered_services = None

    if keyword or keyword.strip():
        filter = { "published" : True, 'is_queue' : False, "$or": [ { 'name' : { '$regex' : keyword, "$options" : "i" } },  { 'description' : { '$regex' : keyword, "$options" : "i" } } ] }
        filtered_services = db_services.get_all_by_filter(filter)

    return filtered_services

def get_published_rmq_services_by_keywords(keyword):
    filtered_services = None

    if keyword or keyword.strip():
        filter = { "published" : True, 'is_queue' : True, "$or": [ { 'name' : { '$regex' : keyword, "$options" : "i" } },  { 'description' : { '$regex' : keyword, "$options" : "i" } } ] }
        filtered_services = db_services.get_all_by_filter(filter)

    return filtered_services

def service_insert(service):
    return db_services.insert(service)

def service_update(updated_service):
    updated_service['last_handler_user'] = get_logged_username()
    updated_service['last_handler_date'] = get_datetime_now()

    return db_services.update(updated_service)

#-- services data --#

def get_service_data_by_id(id):
    return db_services_data.get_by_id(id)

def get_service_data_by_service_id(service_id):
    filter = { 'service_id' : service_id }

    return db_services_data.get_one_by_filter(filter)

def service_data_insert(service_data):
    return db_services_data.insert(service_data)

def service_data_update(updated_service_data):
    return db_services_data.update(updated_service_data)

#-- services history --#

def get_service_history_by_id(id):
    return db_services_history.get_by_id(id)

def get_service_history_by_service_id(service_id):
    filter = { 'service_id' : service_id }

    return db_services_history.get_one_by_filter(filter)

def get_all_service_history_by_service_name(service_name, service_version):
    filter = { 'service_name' : service_name, 'service_version' : { '$lte' : service_version } }
    sort = [('service_version', 1)]

    db_services_history.set_no_pagination(True)
    return db_services_history.get_all_by_filter(filter, sort)

def service_history_insert(service_history):
    return db_services_history.insert(service_history)

def service_history_update(updated_service_history):
    return db_services_history.update(updated_service_history)


### ROUTES ###

@bp.route("/service/list", defaults={'page_num' : 1})
@bp.route("/service/list/<int:page_num>")
@login_required
@editor_required
def service_list(page_num):
    services, total_services = get_published_services_distinct(page_num)
    services_count = len(services)

    pagination = Pagination(total_services, page_num)

    return render_template('service/list.html', rmq=False, pagination=pagination, services=services, services_count=services_count)


@bp.route("/service/<string:service_name>/versions", defaults={'page_num' : 1})
@bp.route("/service/<string:service_name>/versions/<int:page_num>")
@login_required
@editor_required
def service_version_list(service_name, page_num):
    services, total_services = get_published_services_by_name(service_name, page_num)

    pagination = Pagination(total_services, page_num)

    return render_template('service/version.html', pagination=pagination, rmq=False, service_name=service_name, services=services)


@bp.route("/service/detail/<string:id>")
@login_required
@editor_required
def service_detail(id):
    service = get_service_by_id(id)
    service_data = get_service_data_by_service_id(id)
    service_histories = None

    if service:
        service_histories = get_all_service_history_by_service_name(service['name'], service['version'])

    return render_template('service/detail.html', rmq=False, service=service, service_data=service_data, service_histories=service_histories, Markup=Markup)


@bp.route("/queue/list", defaults={'page_num' : 1})
@bp.route("/queue/list/<int:page_num>")
@login_required
@editor_required
def rmq_service_list(page_num):
    services, total_services = get_published_rmq_services_distinct(page_num)
    services_count = len(services)
    pagination = Pagination(total_services, page_num)

    return render_template('service/list.html', pagination=pagination, rmq=True, services=services, services_count=services_count)


@bp.route("/queue/<string:service_name>/versions", defaults={'page_num' : 1})
@bp.route("/queue/<string:service_name>/versions/<int:page_num>")
@login_required
@editor_required
def rmq_service_version_list(service_name, page_num):
    services, total_services = get_published_rmq_services_by_name(service_name, page_num)

    pagination = Pagination(total_services, page_num)

    return render_template('service/version.html', pagination=pagination, rmq=True, service_name=service_name, services=services)


@bp.route("/queue/detail/<string:id>")
@login_required
@editor_required
def rmq_service_detail(id):
    service = get_service_by_id(id)
    service_data = get_service_data_by_service_id(id)
    service_histories = None

    if service:
        service_histories = get_all_service_history_by_service_name(service['name'], service['version'])

    return render_template('service/detail.html', rmq=True, service=service, service_data=service_data, service_histories=service_histories, Markup=Markup)

apidocs/templates/search/list.html
{% extends 'base/template.html' %}

{% block header %}
  {% block title %}Pesquisa{% endblock %}
{% endblock %}

{% block content %}

{% if search_count <= 0 %}

<div class="row">
	<div class="col-lg-12">
        Não foram encontrados resultado para a sua pesquisa por <label class="font-weight-bold">"{{ search_word }}"</label>:
    </div>
</div>

{% else %}

<div class="row">
	<div class="col-lg-12">
        Exibindo {{ search_count }} resultado(s) encontrado(s) para a sua pesquisa por <label class="font-weight-bold">{{ search_word }}</label>:
    </div>
</div>

<hr/>

<div class="row">
	<div class="col-lg-12">
        <div class="card shadow mb-4">
            <a href="#collapseCardApis" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardApis">
                <h6 class="m-0 font-weight-bold text-primary">{{ api_count }} APIs</h6>
            </a>
            <div class="collapse {% if api_count > 0 %}show{% endif %}" id="collapseCardApis">
                <div class="card-body">
                {% if api_count == 0 %}
                    <div class="row">
                        <div class="col-lg-12">
                            <span class="text">Nenhum registro encontrado.</span>
                        </div>
                    </div>
                {% endif %}                
                {% for api in apis %}
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="{{ url_for('api_controller.api_detail', id=api['_id']) }}">{{ api['method'] }} - {{ api['path'] }}  - {{ api['summary'] }}</a>
                        </div>
                    </div>
                {% endfor %}                    
                </div>
            </div>
        </div>
    </div>
</div>

{% if g.user["profile"] == "A" or g.user["profile"] == "E" %}

<div class="row">
	<div class="col-lg-12">
        <div class="card shadow mb-4">
            <a href="#collapseCardOrchs" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardOrchs">
                <h6 class="m-0 font-weight-bold text-primary">{{ orch_count }} Orquestradores</h6>
            </a>
            <div class="collapse {% if orch_count > 0 %}show{% endif %}" id="collapseCardOrchs">
                <div class="card-body">
                {% if orch_count == 0 %}
                    <div class="row">
                        <div class="col-lg-12">
                            <span class="text">Nenhum registro encontrado.</span>
                        </div>
                    </div>
                {% endif %}                
                {% for orch in orchs %}
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="{{ url_for('orch_controller.orch_detail', id=orch['_id']) }}">{{ orch['name'] }} - {{ orch['version'] }}</a>
                        </div>
                    </div>
                {% endfor %}                    
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
	<div class="col-lg-12">
        <div class="card shadow mb-4">
            <a href="#collapseCardServices" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardServices">
                <h6 class="m-0 font-weight-bold text-primary">{{ service_count }} Serviços</h6>
            </a>
            <div class="collapse {% if service_count > 0 %}show{% endif %}" id="collapseCardServices">
                <div class="card-body">
                {% if service_count == 0 %}
                    <div class="row">
                        <div class="col-lg-12">
                            <span class="text">Nenhum registro encontrado.</span>
                        </div>
                    </div>
                {% endif %}                
                {% for service in services %}
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="{{ url_for('service_controller.service_detail', id=service['_id']) }}">{{ service['name'] }} - {{ service['version'] }}</a>
                        </div>
                    </div>
                {% endfor %}                    
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
	<div class="col-lg-12">
        <div class="card shadow mb-4">
            <a href="#collapseCardQueues" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardQueues">
                <h6 class="m-0 font-weight-bold text-primary">{{ queue_count }} Filas</h6>
            </a>
            <div class="collapse {% if queue_count > 0 %}show{% endif %}" id="collapseCardQueues">
                <div class="card-body">
                {% if queue_count == 0 %}
                    <div class="row">
                        <div class="col-lg-12">
                            <span class="text">Nenhum registro encontrado.</span>
                        </div>
                    </div>
                {% endif %}
                {% for queue in queues %}
                    <div class="row">
                        <div class="col-lg-12">
                            <a href="{{ url_for('service_controller.rmq_service_detail', id=queue['_id']) }}">{{ queue['name'] }} - {{ queue['version'] }}</a>
                        </div>
                    </div>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endif %}

{% endif %}

{% endblock %}