apidocs/modules/user/models.py
from flask import (
        Blueprint
)

bp = Blueprint('user_model', __name__)

class UserModel:
    def __init__(self, name, email, password, status, profile):
        self.name = name
        self.email = email
        self.password = password
        self.status = status
        self.profile = profile
    
    def get_model(self):
        model = {
            'name' : self.name, 
            'email' : self.email, 
            'password' : self.password, 
            'status' : self.status, 
            'profile' : self.profile
            }
        
        return model
    
    def save_model(self):
        pass

apidocs/modules/user/controllers.py
from flask import (
        Blueprint, render_template, request, url_for, redirect, flash, g
)

from apidocs.helpers.pagination import Pagination
from apidocs.modules.access_control.manager import login_required, admin_required
from apidocs.modules.audit_log.controllers import audit_log
from apidocs.modules.user.models import UserModel
from apidocs.db.mongodb import MongoDb
from apidocs.helpers.utils import status_list, show_status_text, profile_list, show_profile_text

bp = Blueprint('user_controller', __name__)
db_users = MongoDb('users')

### METHODS ###

def get_active_users():
    return get_users_by_status('A', 1)

def get_users_by_status(status, page_num):
    filter = { 'status' : status }
    sort = [( 'name' , 1 )]

    db_users.set_page_num(page_num)
    return db_users.get_all_by_filter(filter, sort), db_users.count_total(filter)

def get_user_by_id(id):
    return db_users.get_by_id(id)

def get_user(email):
    filter = { 'email' : email }

    return db_users.get_one_by_filter(filter)

def update_user(user):
    result = db_users.update(user)

    return result

def delete_user(user_id):
    result = db_users.delete(user_id)

    return result

def register_new_user(firstname, lastname, email, password):
    model = UserModel(firstname + ' ' + lastname, email, password, 'P', 'U')
    user = model.get_model()
    
    insert_user(user)
    
    return True

def register_new_admin(firstname, lastname, email, password):
    if (get_user(email)):
        return False

    model = UserModel(firstname + ' ' + lastname, email, password, 'A', 'A')
    user = model.get_model()
    
    insert_user(user)
    
    return True

def insert_user(user):
    result = db_users.insert(user)
    
    return result    

def user_update_validation(user, new_password, confirm_new_password):
    error = None

    #Em caso de troca de senha, atualiza o password do usuário, se não, confirma a senha automaticamente
    if not new_password is None and len(new_password) > 0:
        user['password'] = new_password
    else:
        confirm_new_password = user['password']

    if user is None:
        error = 'Usuário não encontrado em nossa base de dados.'
    elif user['name'] is None or not user['name']:
        error = 'Nome não informado.'
    elif user['email'] is None or not user['email']:
        error = 'E-mail não informado.'
    elif not user_update_email_validation(user):
        error = 'E-mail informado já está cadastrado para outro usuário.'        
    elif user['password'] is None or not user['password']:
        error = 'Senha não informada.'
    elif user['password'] != confirm_new_password:
        error = 'As senhas informadas são diferentes.'
    elif user['status'] is None or not user['status']:
        error = 'Situação não informada.'
    elif user['profile'] is None or not user['profile']:
        error = 'Perfil não informado.'                

    return error

def user_update_email_validation(updated_user):
    original_user = get_user_by_id(updated_user['_id'])
    
    #Verifica se o e-mail informado é igual ao e-mail original do usuário, se não, verifica se o e-email novo está em uso
    if updated_user['email'] != original_user['email']:
        users_in_db = get_user(updated_user['email'])

        if users_in_db:
            return False
    
    return True

def user_change(user_id, status):
    user = get_user_by_id(user_id)
    error = None

    if status == "P" or status == "D": #Aprovar ou Reativar
        user['status'] = "A"
        
        error = user_update_validation(user, None, None)

        if error is None:
            update_user(user)

            flash("Usuário {} com sucesso!".format('aprovado' if status == 'P' else 'reativado'), "success")
            
            return True

    elif status == "A": #Salvar Alterações
        new_name = request.form['new_name']
        new_email = request.form['new_email']
        new_password = request.form['new_password']
        confirm_new_password = request.form['confirm_new_password']
        selected_status = request.form['new_status']
        selected_profile = request.form['new_profile']

        user['name'] = new_name
        user['email'] = new_email
        user['status'] = selected_status
        user['profile'] = selected_profile
        
        error = user_update_validation(user, new_password, confirm_new_password)

        if error is None:
            update_user(user)

            flash("Usuário atualizado com sucesso!", "success")        
            
            return True
    
    else:
        error = "Operação Inválida (erro)"

    flash(error, 'error')
    return False

def profile_change(user_id, password):
    fullname = request.form['fullname']
    new_password = request.form['password']
    confirm_password = request.form['confirmpassword']

    user = get_user_by_id(user_id)
    user['name'] = fullname
    user['password'] = password

    error = user_update_validation(user, new_password, confirm_password)

    if error is None:
        update_user(user)

        audit_log("PERFIL ATUALIZADO")

        flash('Perfil atualizado com sucesso!', 'success')
    else:
        flash(error, 'error')


def user_db_remove(user_id):
    try:
        result = delete_user(user_id)
        flash("Usuário foi excluído com sucesso!", 'success')
        return True
    except Exception as ex:
        flash("Ocorreu um erro ao excluir o usuário: {}".format(ex), 'error')
        return False

### ROUTES ###

@bp.route("/user/list/<string:status>", defaults={'page_num' : 1})
@bp.route("/user/list/<string:status>/<int:page_num>")
@login_required
@admin_required
def user_list(status, page_num):
    users, total_users = get_users_by_status(status, page_num)
    pagination = Pagination(total_users, page_num)
    return render_template('user/list.html', pagination=pagination, users=users, status=status, show_status_text=show_status_text, show_profile_text=show_profile_text)

@bp.route("/user/detail/<string:id>/<string:status>")
@login_required
@admin_required
def user_detail(id, status):
    user = get_user_by_id(id)
    return render_template('user/detail.html', user=user, status=status, status_list=status_list, show_status_text=show_status_text, profile_list=profile_list, show_profile_text=show_profile_text)

@bp.route("/user/detail/save", methods=('POST',))
@login_required
@admin_required
def user_detail_save():
    user_id = request.form['user_id']
    status = request.form['status']

    if user_change(user_id, status):
        return redirect(url_for('user_controller.user_list', status="A"))
    else:
        return redirect(url_for('user_controller.user_detail', id=user_id, status=status))

@bp.route("/user/delete", methods=('POST',))
@login_required
@admin_required
def user_delete():
    user_id = request.form['user_to_delete']

    user_db_remove(user_id)
    return redirect(url_for('user_controller.user_list', status="A"))

@bp.route("/profile", methods=('GET', 'POST'))
@login_required
def profile():
    user_id = g.user['_id']

    if request.method == 'POST':
        actual_password = g.user['password']
        profile_change(user_id, actual_password)

    user = get_user_by_id(user_id)

    return render_template('user/profile.html', user=user, show_status_text=show_status_text, show_profile_text=show_profile_text)

apidocs/templates/user/detail.html
{% extends 'base/template.html' %}

{% block header %}
    {% block title %}Detalhes do Usuário{% endblock %}
{% endblock %}

{% block button_back %}

<a href="{{ url_for('user_controller.user_list', status=status) }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
    <i class="fas fa-arrow-left fa-sm text-white-50"></i> Voltar
</a>

{% endblock %}

{% block content %}

<div class="row">
	<div class="col-lg-12">
        <form id="userchanges" name="userchanges" method="post" action="{{ url_for('user_controller.user_detail_save') }}" class="user">
            <input type="hidden" name="user_id" value="{{ user['_id'] }}"></status>
            <input type="hidden" name="status" value="{{ status }}"></status>
            <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">E-mail</label>
                <div class="col-sm-10">
                    <input type="text" {% if status != "A" %}readonly{% endif %} class="form-control{% if status != "A" %}-plaintext{% endif %}" id="new_email" name="new_email" value="{{ user['email'] }}">
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <label for="fullname" class="col-sm-2 col-form-label">Nome</label>
                <div class="col-sm-10">
                    <input type="text" {% if status == 'P' or status == 'D' %}readonly{% endif %} class="form-control{% if status == 'P' or status == 'D' %}-plaintext{% endif %}" id="new_name" name="new_name" value="{{ user['name'] }}">
                </div>
            </div>        
            <div class="form-group row {% if status == 'P' or status == 'D' %}d-none{% endif %}">
                <label for="password" class="col-sm-2 col-form-label">Nova Senha</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="new_password" name="new_password" placeholder="Nova senha...">
                </div>
            </div>
            <div class="form-group row {% if status == 'P' or status == 'D' %}d-none{% endif %}">
                <label for="confirmpassword" class="col-sm-2 col-form-label">Confirme sua nova senha</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="confirm_new_password" name="confirm_new_password" placeholder="Confirme a nova senha...">
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <label for="status" class="col-sm-2 col-form-label">Situação</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext {% if status == "A" %}d-none{% endif %}" id="status_text" name="status_text" value="{{ show_status_text(user['status']) }}">
                    <select id="new_status" name="new_status" class="form-control {% if status != "A" %}d-none{% endif %}">
                        {% for key, value in status_list().items() %}
                        <option {% if key == user['status'] %}selected="true"{% endif %} value= '{{ key }}'>{{value}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="status" class="col-sm-2 col-form-label">Perfil</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext {% if status == "A" %}d-none{% endif %}" id="profile_text" name="profile_text" value="{{ show_profile_text(user['profile']) }}">
                    <select id="new_profile" name="new_profile" class="form-control {% if status != "A" %}d-none{% endif %}">
                        {% for key, value in profile_list().items() %}
                        <option {% if key == user['profile'] %}selected="true"{% endif %} value= '{{ key }}'>{{value}}</option>
                        {% endfor %}
                    </select>                    
                </div>
            </div>            
            <hr />
            <div class="form-group row">
                {% if status == "A" %}            
                <button type="submit" form="userchanges" class="btn btn-primary btn-sm ml-1">
                    Salvar Alterações
                </button>
                {% else %}                
                <button type="submit" form="userchanges" class="btn btn-success btn-sm ml-1">
                    {% if status == 'P' %}Aprovar{% elif status == 'D' %}Reativar{% endif %}
                </button>
                {% endif %}
            </div>  
        </form>    
	</div>
</div>

{% endblock %}

apidocs/templates/user/list.html
{% import "macros/_macros.html" as macros %}
{% extends 'base/template.html' %}

{% block header %}
    {% block title %}Lista de Usuários - {{ show_status_text(status) }}{% endblock %}
{% endblock %}

{% block button_back %}

<a href="{{ url_for('register_controller.new_user_register') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">
    <i class="fas fa-plus fa-sm text-white-50"></i> Novo Usuário
</a>

{% endblock %}

{% block content %}

<div class="row">
	<div class="col-lg-12">
        <div class="row mb-4">
            <div class="col-lg-9">
                <span class="text font-weight-bolder">Visualizar somente usuários:</span>
                <a class="btn btn-success btn-sm ml-1" href="{{ url_for('user_controller.user_list', status='A') }}">{{ show_status_text('A') }}</a>
                <a class="btn btn-danger btn-sm ml-1" href="{{ url_for('user_controller.user_list', status='D') }}">{{ show_status_text('D') }}</a>
                <a class="btn btn-warning btn-sm ml-1" href="{{ url_for('user_controller.user_list', status='P') }}">{{ show_status_text('P') }}</a>
            </div>
        </div>
        {% if users.count() > 0 %}
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Nome do usuário</th>
                        <th>E-mail de acesso</th>
                        <th>Situação atual</th>
                        <th>Perfil de sistema</th>
                        <th>Opções</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                    <tr>
                        <td>{{ user['name'] }}</td>
                        <td>{{ user['email'] }}</td>
                        <td>{{ show_status_text(user['status']) }}</td>
                        <td>{{ show_profile_text(user['profile']) }}</td>
                        <td>
                            <a class="btn btn-icon-split btn-primary btn-sm" href="{{ url_for('user_controller.user_detail', id=user['_id'], status=user['status']) }}">
                                <span class="icon text-white-50">
                                    <i class="fas fa-edit"></i>
                                </span>
                                <span class="text">Editar</span>
                            </a>
                            <a class="btn btn-icon-split btn-primary btn-sm" href="#" onclick="showModalDelete('{{ user['_id'] }}');">
                                <span class="icon text-white-50">
                                    <i class="fas fa-trash"></i>
                                </span>
                                <span class="text">Excluir</span>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <div class="card mb-4 py-3 border-left-warning text-center">Sem registros de usuários para serem exibidos, no momento!</div>
        {% endif %}
    </div>
</div>

  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Excluir Usuário?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <form id="userdelete" name="userdelete" method="post" action="{{ url_for('user_controller.user_delete') }}">
            <input type="hidden" id="user_to_delete" name="user_to_delete" />
        </form>
        <div class="modal-body">Selecione "Excluir" abaixo se você realmente deseja excluir o usuário selecionado.</div>
        <div class="modal-footer text-center">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Fechar</button>
          <button class="btn btn-primary" type="submit" form="userdelete">Excluir</button>
        </div>
      </div>
    </div>
  </div>

    {{ macros.pagination_widget(pagination.pages_array, pagination.actual_page, 'user_controller.user_list', status=status) }}

{% endblock %}

{% block script %}

    <script type="text/javascript">
        function showModalDelete(user_id) {
            $('#user_to_delete').val(user_id);

            $('#deleteModal').modal('show');
        }
    </script>

{% endblock %}

apidocs/templates/user/profile.html
{% extends 'base/template.html' %}

{% block header %}
  {% block title %}Perfil{% endblock %}
{% endblock %}

{% block content %}

<div class="row">
	<div class="col-lg-12">
        <form id="profilechanges" name="profilechanges" method="post" action="{{ url_for('user_controller.profile') }}" class="user">
            <div class="form-group row">
                <label for="email" class="col-sm-2 col-form-label">E-mail</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" id="email" name="email" value="{{ user['email'] }}">
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <label for="fullname" class="col-sm-2 col-form-label">Nome</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="fullname" name="fullname" value="{{ user['name'] }}">
                </div>
            </div>        
            <div class="form-group row">
                <label for="password" class="col-sm-2 col-form-label">Nova Senha</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="password" name="password" placeholder="Nova senha...">
                </div>
            </div>
            <div class="form-group row">
                <label for="confirmpassword" class="col-sm-2 col-form-label">Confirme sua nova senha</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" id="confirmpassword" name="confirmpassword" placeholder="Confirme a nova senha...">
                </div>
            </div>
            <hr />
            <div class="form-group row">
                <label for="status" class="col-sm-2 col-form-label">Situação</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" id="status" name="status" value="{{ show_status_text(user['status']) }}">
                </div>
            </div>
            <div class="form-group row">
                <label for="status" class="col-sm-2 col-form-label">Perfil</label>
                <div class="col-sm-10">
                    <input type="text" readonly class="form-control-plaintext" id="profile" name="profile" value="{{ show_profile_text(user['profile']) }}">
                </div>
            </div>            
            <hr />
            <div class="form-group row">
                <button type="submit" form="profilechanges" class="btn btn-primary">
                    Salvar Alterações
                </button>
            </div>  
        </form>    
	</div>
</div>

{% endblock %}

{% block script %}

{% endblock %}